name: Docker Build & Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [__placeholder__]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image version
        id: version
        run: |
          echo "tag=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./src/Services/${{ matrix.service }}
          file: ./src/Services/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/micromarket-${{ matrix.service }}:${{ steps.version.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/micromarket-${{ matrix.service }}:latest
